### ISSUE TITLE
One-way mirrors

### ISSUE THREAD

**Issue by TheKnarf** [tsoding/ray-tracer#12]

**Comment by rexim** [comment]
@TheKnarf btw do you remember what exactly we wanted to achive in this issue? :)

**Comment by TheKnarf** [comment]
Not entirely sure, the chat mentioned one-way mirrors (also called "two-way mirrors" confusingly enough). Perhaps a material that let rays go through one way but reflect the other?

If it's no longer interesting then we can just as well close the issue.

**Comment by rexim** [comment]
@TheKnarf Ah, yeah! I think it was a counterexample for the statement that tracing the rays camera-lightsource produces the same picture as tracing lightsource-camera. It sounds interesting to try to verify, but feels slightly outside of the scope of this project. Let's close it for now. Thanks for bringing it up anyway. :)
