### ISSUE TITLE
Downgrade to C++14

### ISSUE THREAD

**Issue by rexim** [tsoding/ray-tracer#60]
People are having to much trouble building the project.

**Comment by notzain** [comment]
Is this an issue you want to fix yourself/on stream?

There are some issues that might need more attention, and you should decide yourself what to do (i.e, finding an alternative to C++17-only std::optional). 

If you're okay with it, I would like to make an attempt as well.

**Comment by rexim** [comment]
@notzain Oh yeah, feel free take this issue! Keep in mind that a big change coming from #59. I will finish #59 today or tommorow. I'm not planning to touch the code much after that until the [next ray-tracer stream](https://tsoding.github.io/schedule/#_1535472000) so you have a whole week. :)

**Comment by rexim** [comment]
@notzain regarding what to do, I'd go with downgrading to C++17 and getting rid of optional completely. We may try to replace it with an alternative but that will require to change the build and CI which is too much of a hassle IMO. But feel free to suggest anything you want. We can always discuss everything in the PR. :)

**Comment by rexim** [comment]
Resolved by #61
